/** ACTION TYPES */

export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const GET_COLOR = 'GET_COLOR';
export const FETCH_HEROES_LIST = 'FETCH_HEROES_LIST';
export const STORE_USER_LOGIN_DATA = 'STORE_USER_LOGIN_DATA';
export const STORE_CUSTOMER_CARD_DETAILS = 'STORE_CUSTOMER_CARD_DETAILS';
export const STORE_KEY_EXCHANGE_API_DETAILS = 'STORE_KEY_EXCHANGE_API_DETAILS';
